dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -q pytest pytest-pep8
  - pip install -q coverage coveralls
script:
  - coverage run --source typetalk -m py.test --pep8
after_success:
  - coveralls
notifications:
  email: false
